server:
  port: 8080

# Liquibase 配置
#liquibase:
#  url: jdbc:mysql://localhost:3306/java5?useUnicode=true&amp;characterEncoding=utf-8
#  driver: com.mysql.jdbc.Driver
#  password: root
#  username: admin
#  enabled: true
#  change-log: classpath:liquibase/changelog/master.xml

spring:
  jpa:
    generate-ddl: true # 是不是自动生产SQL语句
    show-sql: true # 是不是显示执行的SQL语句
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  # 配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/java5?useUnicode=true&characterEncoding=utf8&autoReconnect=true&characterSetResults=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: admin

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

jwt:
  secret: secret             # 用于生成token的密钥
  expiration: 7200000   # token有效期
  token: Authorization   # http header里token 所在的字段名